-- Script de criação de tabelas

create table usuarios (
    id serial primary key,
    nome varchar(100) not null,
    email varchar(100) not null unique,
    senha varchar(255) not null
);

comment on table usuarios is 'Tabela de usuários do sistema';
comment on column usuarios.id is 'ID do usuário';
comment on column usuarios.nome is 'Nome do usuário';
comment on column usuarios.email is 'Email do usuário';
comment on column usuarios.senha is 'Senha criptografada';


insert into usuarios (nome, email, senha)
values ('Administrador', 'admin@devbarbershop.com', crypt('admin123', gen_salt('bf')));
-----------------------------------------------------------------------------------------------

create table cliente(
    codcli int generated by default as identity primary key,
    nomcli varchar(150) not null,
    telcli varchar(20) not null,
    emailcli varchar(100) not null,
    bairrocli varchar(100) not null,
    ruaendcli varchar(100) not null,
    sexocli varchar(10) not null,
    cidadecli varchar(50) not null,
    dtnascli date not null
);

comment on table cliente is 'Tabela de clientes da Barbearia';
comment on column cliente.codcli is 'Código do cliente';
comment on column cliente.nomcli is 'Nome do cliente';
comment on column cliente.telcli is 'Telefone do cliente';
comment on column cliente.emailcli is 'E-mail do cliente';
comment on column cliente.bairrocli is 'Bairro do cliente';
comment on column cliente.ruaendcli is 'Rua do endereço do cliente';
comment on column cliente.sexocli is 'Sexo do cliente';
comment on column cliente.cidadecli is 'Cidade do cliente';
comment on column cliente.dtnascli is 'Data de nascimento do cliente';

-----------------------------------------------------------------------------------------------

create table fornecedor(
    codforn int generated by default as identity primary key,
    nomeforn varchar(150) not null,
    telforn varchar(20),
    emailforn varchar(100),
    enderecoforn varchar(100)
);

comment on table fornecedor is 'Tabela de fornecedores';
comment on column fornecedor.codforn is 'Código do fornecedor';
comment on column fornecedor.nomeforn is 'Nome do fornecedor';
comment on column fornecedor.telforn is 'Telefone do fornecedor';
comment on column fornecedor.emailforn is 'E-mail do fornecedor';
comment on column fornecedor.enderecoforn is 'Endereço do fornecedor';

-----------------------------------------------------------------------------------------------

create table funcionario(
    codfun int generated by default as identity primary key,
    nomefun varchar(100) not null,
    telfun varchar(20) not null,
    emailfun varchar(100) not null,
    cargofun varchar(100) not null,
    salariofun numeric(10, 2) not null
);

comment on table funcionario is 'Tabela de funcionários da Barbearia';
comment on column funcionario.codfun is 'Código do funcionário';
comment on column funcionario.nomefun is 'Nome do funcionário';
comment on column funcionario.telfun is 'Telefone do funcionário';
comment on column funcionario.emailfun is 'E-mail do funcionário';
comment on column funcionario.cargofun is 'Cargo do funcionário';
comment on column funcionario.salariofun is 'Salário do funcionário';

-----------------------------------------------------------------------------------------------

create table servico(
    codserv int generated by default as identity primary key,
    nomeserv varchar(100) not null,
    descserv varchar(100),
    precoserv numeric(10, 2) not null
);

comment on table servico is 'Tabela de serviços oferecidos pela Barbearia';
comment on column servico.codserv is 'Código do Serviço';
comment on column servico.nomeserv is 'Nome do serviço';
comment on column servico.descserv is 'Descrição do serviço oferecido pela Barbearia';
comment on column servico.precoserv is 'Preço dos serviços oferecidos pela Barbearia';

-----------------------------------------------------------------------------------------------

create table produto(
    codprod int generated by default as identity primary key,
    nomeprod varchar(100) not null,
    descprod varchar(255),
    qtdprod int not null,
    precoprod numeric(10, 2) not null,
    fornecedorcodforn int references fornecedor(codforn),
    servicocodserv int references servico(codserv)
);

comment on table produto is 'Tabela de produtos';
comment on column produto.codprod is 'Código do produto';
comment on column produto.nomeprod is 'Nome do produto';
comment on column produto.descprod is 'Descrição do produto';
comment on column produto.qtdprod is 'Quantidade do produto em estoque';
comment on column produto.precoprod is 'Preço do produto';
comment on column produto.fornecedorcodforn is 'Código do fornecedor do produto';
comment on column produto.servicocodserv is 'Código do serviço relacionado ao produto';

-----------------------------------------------------------------------------------------------

create table agendamento(
    codagen int generated by default as identity primary key,
    data_hora timestamp not null,
    status varchar(50) not null,
    clientecodcli int references cliente(codcli),
    funcionariocodfun int references funcionario(codfun)
);

comment on table agendamento is 'Tabela de agendamentos';
comment on column agendamento.codagen is 'Código do agendamento';
comment on column agendamento.data_hora is 'Data e hora do agendamento';
comment on column agendamento.status is 'Status do agendamento';
comment on column agendamento.clientecodcli is 'Código do cliente';
comment on column agendamento.funcionariocodfun is 'Código do funcionário';

-----------------------------------------------------------------------------------------------

create table pagamento(
    codpag int generated by default as identity primary key,
    valor numeric(10, 2) not null,
    data_hora_pagamento timestamp not null,
    forma_pagamento varchar(50) not null,
    clientecodcli int references cliente(codcli),
    agendamentocodagen int references agendamento(codagen)
);

comment on table pagamento is 'Tabela de pagamentos';
comment on column pagamento.codpag is 'Código do pagamento';
comment on column pagamento.valor is 'Valor do pagamento';
comment on column pagamento.data_hora_pagamento is 'Data e hora do pagamento';
comment on column pagamento.forma_pagamento is 'Forma de pagamento';
comment on column pagamento.clientecodcli is 'Código do cliente';
comment on column pagamento.agendamentocodagen is 'Código do agendamento';

-----------------------------------------------------------------------------------------------

create table historico_servico(
    codhistorico int generated by default as identity primary key,
    data_hora timestamp not null,
    servicocodserv int references servico(codserv),
    clientecodcli int references cliente(codcli),
    funcionariocodfun int references funcionario(codfun)
);

comment on table historico_servico is 'Tabela de histórico de serviços prestados';
comment on column historico_servico.codhistorico is 'Código do histórico de serviço';
comment on column historico_servico.data_hora is 'Data e hora do serviço';
comment on column historico_servico.servicocodserv is 'Código do serviço';
comment on column historico_servico.clientecodcli is 'Código do cliente';
comment on column historico_servico.funcionariocodfun is 'Código do funcionário';